# Generated by Django 3.1.3 on 2020-11-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201114_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
